'AAA BBB CCC DDD EEE FFF GGG AA BB CC DD EE FF GG A B C D E F G a b c d e f g aa bb cc dd ee ff gg'

['AAAflat',
 'AAA',
 'AAAsharp',
 'BBBflat',
 'BBB',
 'BBBsharp',
 'CCCflat',
 'CCC',
 'CCCsharp',
 'DDDflat',
 'DDD',
 'DDDsharp',
 'EEEflat',
 'EEE',
 'EEEsharp',
 'FFFflat',
 'FFF',
 'FFFsharp',
 'GGGflat',
 'GGG',
 'GGGsharp',
 'AAflat',
 'AA',
 'AAsharp',
 'BBflat',
 'BB',
 'BBsharp',
 'CCflat',
 'CC',
 'CCsharp',
 'DDflat',
 'DD',
 'DDsharp',
 'EEflat',
 'EE',
 'EEsharp',
 'FFflat',
 'FF',
 'FFsharp',
 'GGflat',
 'GG',
 'GGsharp',
 'Aflat',
 'A',
 'Asharp',
 'Bflat',
 'B',
 'Bsharp',
 'Cflat',
 'C',
 'Csharp',
 'Dflat',
 'D',
 'Dsharp',
 'Eflat',
 'E',
 'Esharp',
 'Fflat',
 'F',
 'Fsharp',
 'Gflat',
 'G',
 'Gsharp',
 'aflat',
 'a',
 'asharp',
 'bflat',
 'b',
 'bsharp',
 'cflat',
 'c',
 'csharp',
 'dflat',
 'd',
 'dsharp',
 'eflat',
 'e',
 'esharp',
 'fflat',
 'f',
 'fsharp',
 'gflat',
 'g',
 'gsharp',
 'aaflat',
 'aa',
 'aasharp',
 'bbflat',
 'bb',
 'bbsharp',
 'ccflat',
 'cc',
 'ccsharp',
 'ddflat',
 'dd',
 'ddsharp',
 'eeflat',
 'ee',
 'eesharp',
 'ffflat',
 'ff',
 'ffsharp',
 'ggflat',
 'gg',
 'ggsharp']

na ={'A': 43,
 'AA': 22,
 'AAA': 1,
 'AAAflat': 0,
 'AAAsharp': 2,
 'AAflat': 21,
 'AAsharp': 23,
 'Aflat': 42,
 'Asharp': 44,
 'B': 46,
 'BB': 25,
 'BBB': 4,
 'BBBflat': 3,
 'BBBsharp': 5,
 'BBflat': 24,
 'BBsharp': 26,
 'Bflat': 45,
 'Bsharp': 47,
 'C': 49,
 'CC': 28,
 'CCC': 7,
 'CCCflat': 6,
 'CCCsharp': 8,
 'CCflat': 27,
 'CCsharp': 29,
 'Cflat': 48,
 'Csharp': 50,
 'D': 52,
 'DD': 31,
 'DDD': 10,
 'DDDflat': 9,
 'DDDsharp': 11,
 'DDflat': 30,
 'DDsharp': 32,
 'Dflat': 51,
 'Dsharp': 53,
 'E': 55,
 'EE': 34,
 'EEE': 13,
 'EEEflat': 12,
 'EEEsharp': 14,
 'EEflat': 33,
 'EEsharp': 35,
 'Eflat': 54,
 'Esharp': 56,
 'F': 58,
 'FF': 37,
 'FFF': 16,
 'FFFflat': 15,
 'FFFsharp': 17,
 'FFflat': 36,
 'FFsharp': 38,
 'Fflat': 57,
 'Fsharp': 59,
 'G': 61,
 'GG': 40,
 'GGG': 19,
 'GGGflat': 18,
 'GGGsharp': 20,
 'GGflat': 39,
 'GGsharp': 41,
 'Gflat': 60,
 'Gsharp': 62,
 'a': 64,
 'aa': 85,
 'aaflat': 84,
 'aasharp': 86,
 'aflat': 63,
 'asharp': 65,
 'b': 67,
 'bb': 88,
 'bbflat': 87,
 'bbsharp': 89,
 'bflat': 66,
 'bsharp': 68,
 'c': 70,
 'cc': 91,
 'ccflat': 90,
 'ccsharp': 92,
 'cflat': 69,
 'csharp': 71,
 'd': 73,
 'dd': 94,
 'ddflat': 93,
 'ddsharp': 95,
 'dflat': 72,
 'dsharp': 74,
 'e': 76,
 'ee': 97,
 'eeflat': 96,
 'eesharp': 98,
 'eflat': 75,
 'esharp': 77,
 'f': 79,
 'ff': 100,
 'ffflat': 99,
 'fflat': 78,
 'ffsharp': 101,
 'fsharp': 80,
 'g': 82,
 'gflat': 81,
 'gg': 103,
 'ggflat': 102,
 'ggsharp': 104,
 'gsharp': 83}

notes_numera = {0: 'AAAflat',
 1: 'AAA',
 2: 'AAAsharp',
 3: 'BBBflat',
 4: 'BBB',
 5: 'BBBsharp',
 6: 'CCCflat',
 7: 'CCC',
 8: 'CCCsharp',
 9: 'DDDflat',
 10: 'DDD',
 11: 'DDDsharp',
 12: 'EEEflat',
 13: 'EEE',
 14: 'EEEsharp',
 15: 'FFFflat',
 16: 'FFF',
 17: 'FFFsharp',
 18: 'GGGflat',
 19: 'GGG',
 20: 'GGGsharp',
 21: 'AAflat',
 22: 'AA',
 23: 'AAsharp',
 24: 'BBflat',
 25: 'BB',
 26: 'BBsharp',
 27: 'CCflat',
 28: 'CC',
 29: 'CCsharp',
 30: 'DDflat',
 31: 'DD',
 32: 'DDsharp',
 33: 'EEflat',
 34: 'EE',
 35: 'EEsharp',
 36: 'FFflat',
 37: 'FF',
 38: 'FFsharp',
 39: 'GGflat',
 40: 'GG',
 41: 'GGsharp',
 42: 'Aflat',
 43: 'A',
 44: 'Asharp',
 45: 'Bflat',
 46: 'B',
 47: 'Bsharp',
 48: 'Cflat',
 49: 'C',
 50: 'Csharp',
 51: 'Dflat',
 52: 'D',
 53: 'Dsharp',
 54: 'Eflat',
 55: 'E',
 56: 'Esharp',
 57: 'Fflat',
 58: 'F',
 59: 'Fsharp',
 60: 'Gflat',
 61: 'G',
 62: 'Gsharp',
 63: 'aflat',
 64: 'a',
 65: 'asharp',
 66: 'bflat',
 67: 'b',
 68: 'bsharp',
 69: 'cflat',
 70: 'c',
 71: 'csharp',
 72: 'dflat',
 73: 'd',
 74: 'dsharp',
 75: 'eflat',
 76: 'e',
 77: 'esharp',
 78: 'fflat',
 79: 'f',
 80: 'fsharp',
 81: 'gflat',
 82: 'g',
 83: 'gsharp',
 84: 'aaflat',
 85: 'aa',
 86: 'aasharp',
 87: 'bbflat',
 88: 'bb',
 89: 'bbsharp',
 90: 'ccflat',
 91: 'cc',
 92: 'ccsharp',
 93: 'ddflat',
 94: 'dd',
 95: 'ddsharp',
 96: 'eeflat',
 97: 'ee',
 98: 'eesharp',
 99: 'ffflat',
 100: 'ff',
 101: 'ffsharp',
 102: 'ggflat',
 103: 'gg',
 104: 'ggsharp'}

chords = {'cmajt':['c','e','g'],
'csharpmajt': ['csharp','f','gsharp'],
'dmajt':['d','fsharp','a'],
'dsharpmajt': ['dsharp','g','asharp'],
'emajt':['e','gsharp','b'],
'fmajt':['f','a','cc'],
'gmajt':['g','b','dd'],
'amajt':['a','ccsharp','ee'],
'cmaj7':['c','e','g','bbflat']}



index=0

yes_or_no = 'yes'

while (yes_or_no =='yes'):
    print ('                   ')
    print ('Look up chord here:')
    chord_in_question = raw_input()
    notes = chords[chord_in_question]
    print ('Here are the musical notes for the chord:')
    print notes

    print ('Here are the numbers from the dictionary:')
    while (index < len(notes)):
        print na[notes[index]]
        index = index + 1
    print('Would you like to look up another chord?')
    index = 0
    yes_or_no= raw_input() 
    
if (yes_or_no != 'yes'):
    print('Alright, forget it!')